server:
  port: 8001

eureka:
  instance:
    hostname: localhost
  datacenter: cloud
  environment: proudct
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/